In [ ]:
!pip install numpy

In [ ]:
import numpy as np

# Creating array using numpy
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
# This is an 2D array
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of Numpy
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) #Output: (2,3)
print("Number of Dimensions:", arr.ndim) # Output: 2
print("Size (Number of Element Present):", arr.size)
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
Size (Number of Element Present): 6
Data type: int64
Item size (in bytes): 8


In [ ]:
# Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Element wise array
print("Addition:", arr1 + arr2)

#Element wise subsraction
print("Substraction:", arr1 - arr2)

#Element wise multiplication
print("Multiplication:", arr1 * arr2)

#Element wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
#Universal Function
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
# Array Slicing and Indexing Operations
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array:\n ", arr)

Array:
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [ ]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [ ]:
#MOdify array Elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
## Statistical Conpect --Normilization
## To have the mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])
#Calculate the mean and SD
mean = np.mean(data)
std_div = np.std(data)

#Normalzie the data
normilization_data = (data - mean) / std_div
print("Normilized Data:", normilization_data)

Normilized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
# logical Opreation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >5) & (data < 8)]

array([6, 7])